apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-server-client-config
  namespace: default
data:
  K8S_NAMESPACE: "default"
  BMH_API_GROUP: "metal3.io"
  BMH_API_VERSION: "v1alpha1"
  BMH_PLURAL: "baremetalhosts"
  
  # --- Parametri Infrastruttura ---
  PROVISIONING_TIMEOUT: "3600"
  LOG_LEVEL: "INFO"
  DISABLE_HEALTHZ_LOGS: "true"

  # --- Notifiche ---
  #NOTIFICATION_ENDPOINT: "http://127.0.0.1/api/notifications/webhook"
  NOTIFICATION_ENDPOINT: "http://prognose-dev-be-service.prognose-dev.svc.cluster.local:8080/api/notifications/webhook"
  NOTIFICATION_TIMEOUT: "10"
  #WEBHOOK_LOG_ENDPOINT: "http://127.0.0.1/api/webhooks/log"
  WEBHOOK_LOG_ENDPOINT: "http://prognose-dev-be-service.prognose-dev.svc.cluster.local:8080/api/webhooks/log"
  WEBHOOK_LOG_TIMEOUT: "10"
  
 