apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-server-client-sa
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-client-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-client-metal3-role
rules:
- apiGroups: ["metal3.io"]
  resources: ["baremetalhosts"]
  verbs: ["get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-client-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-client-role
subjects:
- kind: ServiceAccount
  name: webhook-server-client-sa
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-client-metal3-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-client-metal3-role
subjects:
- kind: ServiceAccount
  name: webhook-server-client-sa
  namespace: default
