apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-client-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded webhook secret - replace with your actual secret
  # To encode: echo -n "your-webhook-secret" | base64
  # Base64 encoded value of the secret proposed in the web-app
  #WEBHOOK_SECRET: amR3L0lzTHAvQ0JZTFVualJ6dGRJZ3JSQTJud1l6RVM3ODYwSTRZYmx1OD0=
  WEBHOOK_SECRET: SDljUlhrQ1dKUEY2ZWpORG5xV3p4Vnl0aU4rUDBFbW5MZkMrbkpsVWF0RT0=
