apiVersion: v1
kind: Service
metadata:
  name: webhook-server-client-service
  namespace: default
  labels:
    app: webhook-server-client
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: webhook-server-client
